# -*- coding: utf-8 -*-
"""SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-X35b1XIT7sYhC47Td-FmzREwXeeGySz
"""

import sqlite3

# Create a new SQLite database or connect to an existing one
conn = sqlite3.connect('example.db')

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

# Example: Create a table
cursor.execute('''
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT,
    age INTEGER
)
''')

# Insert data
cursor.execute('''
INSERT INTO users (name, age) VALUES (?, ?)
''', ('Alice', 30))
cursor.execute('''
INSERT INTO users (name, age) VALUES (?, ?)''',
 ('Naman',21))


# Commit changes and close the connection
conn.commit()

# Query data
cursor.execute('SELECT * FROM users')
print(cursor.fetchall())

conn.close()

import sqlite3

# Create a new SQLite database or connect to an existing one
conn = sqlite3.connect('student2.db')

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT,
    age INTEGER
)
''')


cursor.execute('''
INSERT INTO users (name,age) VALUES (?,?)''',
 ('ram',23))

conn.commit()

# Query data
cursor.execute('SELECT * FROM users')
print(cursor.fetchall())

conn.close()

import sqlite3
conn = sqlite3.connect('college.db')
cursor= conn.cursor()

cursor.execute(
    '''CREATE TABLE STUDENTss(
    ID INTEGER PRIMARY KEY,
    NAME TEXT ,
     MARKS INTEGER)''')
data = [(121,"Naman",56),
        (122,"aman",54),
        (123,"seema",45)
  ]
cursor.executemany('''
    INSERT INTO STUDENTss (ID,NAME,MARKS) VALUES (?,?,?)''',data

)
conn.commit()
cursor.execute('SELECT*FROM STUDENTss')
print(cursor.fetchall())
conn.close()

