# -*- coding: utf-8 -*-
"""Test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCSYRLHkNu8SsNvhygK2abmvzr4zrWpO
"""

#1
name= input("enter the company's name: ")

for a in set(name):
    count=0
    for b in name:
        if (a==b):
            count+=1
    print(a, count)

#4

a = int(input())
b = []

def insert():
  i=0
  while i < a:
    name = (input("enter the name"))
    if name not in b:
            b.append(name)
    else:
      pass
    i+=1
insert()

print(len(b))

#2
import math
import random
import re
import sys

if __name__ == '__main__':

    nm = input().split()

n = int(nm[0])

m = int(nm[1])

arr = []

for i in range(n):

    arr.append(list(map(int, input().rstrip().split())))

k = int(input())

answer=sorted(arr, key=lambda x:x[k])
print(answer)

#3
from datetime import datetime

def calculate_time_difference(timestamp1, timestamp2):

    time_format = "%a %d %b %Y %H:%M:%S %z"

    datetime1 = datetime.strptime(timestamp1, time_format)
    datetime2 = datetime.strptime(timestamp2, time_format)
    time_difference = abs((datetime1 - datetime2).total_seconds())
    return str(int(time_difference))

if __name__ == "__main__":
    test_cases = int(input("Enter the number of test cases: "))

    for _ in range(test_cases):
        timestamp1 = input("Enter first timestamp: ").strip()
        timestamp2 = input("Enter second timestamp: ").strip()
        result = calculate_time_difference(timestamp1, timestamp2)
        print("Time difference in seconds:", result)