# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZaGnksoWlacLCSqYzaCw2rYlxSpAmb-
"""

rows = int(input("Enter number of rows: "))
for i in range(rows):
    for j in range(i+1):
        print("* ", end="")
    print()

rows = 5
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end=' ')
    print('')

i = 1
while i<=10:
    print(i)
    i += 1

rows = int(input("Enter number of rows: "))
for i in range(1,rows+1):
    for j in range(1,rows-i+1):
        print(" ", end="")
        for j in range(1, 2 * i):
          print("*", end="")

        print()

N = int(input("Enter number of rows: "))


for i in range(1, N + 1):

    for j in range(1, N - i + 1):
        print("  ", end="")


    for j in range(1, 2 * i):
        print("*", end="")

    print()

n = 2
for i in range (1,11,1):
  p = n*i
  print(p)

n = [12, 75, 150, 180, 145, 525, 50]
for elements in n :

  if  elements % 5 == 0 :
    print(elements)

#factorial of any number
num = int(input("Enter a number "))
factorial = 1
if num<0 :
  print("factorial of negative number do not exist ")
elif num == 0 :
  print("factoril of 0 is 1")
else:
  for i in range(1,num+1):
    factorial = factorial*i
  print("the factorial of",num,"is",factorial)

num = int(input("Enter a number "))
for i in range(0, num):
    for j in range(0, i + 1):
        print("*", end=' ')
    print("")

for i in range(num, 0, -1):
    for j in range(0, i - 1):
        print("*", end=' ')
    print("")

n = 10

start = 4
sum_seq = 0
for i in range(0, n):
    print(start, end="+")
    sum_seq += start
    start = start * 10 + 4
print( sum_seq)
#this is a change

n = 10
k = 10
for i in range(0,n+1):
    for j in range(k-i,0,-1):
        print(j,end=' ')
    print()

